export class Estabelecimento {
    constructor(
      public id: string,
      public nome: string,
      public razao: string,
      public cnpj: string,
      public cro: string,
      public endereco: string,
      public numero: string,
      public celular: string,
      public cep: string,
      public bairro: string,
      public cidade: string,
      public estado: string,
      public created: Date,
      public updated: Date,
      public descricao: string,
      public instagram: string,
      public link: string,
      public status: string,
      public paidStatus: boolean,
      public especialidades: string[],
      public comentariosId: string,
      public planoId: string,
      public telefoneVerificado: boolean,
      public senha: string,
      public email: string,
      public foto?: string,
      public codigo?: string,
      public dateLastPayment?: Date,
      public exibirNumero?: boolean,
    ) {}
  }
  