export class Estabelecimento {
    constructor(
      public id: string,
      public nome: string,
      public razao: string,
      public cnpj: string,
      public croResponsavel: string,
      public endereco: string,
      public numero: string,
      public cep: string,
      public cidade: string,
      public estado: string,
      public created: Date,
      public updated: Date,
      public descricao: string,
      public facebook: string,
      public instagram: string,
      public link: string,
      public status: string,
      public paidStatus: boolean,
      public dateLastPayment: Date,
      public especialidadeId: string,
      public comentariosId: string,
      public planoId: string,
      public telefoneVerificado: boolean,
      public senha: string,
      public email: string,
      public foto?: string,
    ) {}
  }
  